version: "3.4"
services:
  ruby-githubstars:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
    logging:
      driver: json-file
    stdin_open: true
    tty: true
    command: /bin/sh
